Remove Bash specific code

diff --git a/execsnoop b/execsnoop
--- a/execsnoop
+++ b/execsnoop
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # execsnoop - trace process exec() with arguments.
 #             Written using Linux ftrace.
@@ -60,7 +60,7 @@ opt_duration=0; duration=; opt_name=0; name=; opt_time=0; opt_reexec=0
 opt_argc=0; argc=8; max_argc=16; ftext=
 trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: execsnoop [-hrt] [-a argc] [-d secs] [name]
 	                 -d seconds      # trace duration, and use buffers
@@ -80,13 +80,13 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function end {
+end() {
 	# disable tracing
 	echo 2>/dev/null
 	echo "Ending tracing..." 2>/dev/null
@@ -95,15 +95,15 @@ function end {
 	warn "echo 0 > events/sched/sched_process_fork/enable"
 	warn "echo -:$kname >> kprobe_events"
 	warn "echo > trace"
-	(( wroteflock )) && warn "rm $flock"
+	! [ $wroteflock -eq 0 ] && warn "rm $flock"
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
 
-function edie {
+edie() {
 	# die with a quiet end()
 	echo >&2 "$@"
 	exec >/dev/null 2>&1
@@ -122,31 +122,31 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
-if (( $# )); then
+shift $(( OPTIND - 1 ))
+if ! [ $# -eq 0 ]; then
 	opt_name=1
 	name=$1
 	shift
 fi
-(( $# )) && usage
+! [ $# -eq 0 ] && usage
 
 ### option logic
-(( opt_name )) && ftext=" issued by process name \"$name\""
-(( opt_argc && argc > max_argc )) && die "ERROR: max -a argc is $max_argc."
-if (( opt_duration )); then
+! [ $opt_name -eq 0 ] && ftext=" issued by process name \"$name\""
+! [ $opt_argc -eq 0 ] && [ "$argc" -gt "$max_argc" ] && die "ERROR: max -a argc is $max_argc."
+if ! [ $opt_duration -eq 0 ]; then
 	echo "Tracing exec()s$ftext for $duration seconds (buffered)..."
 else
 	echo "Tracing exec()s$ftext. Ctrl-C to end."
 fi
 
 ### select awk
-if (( opt_duration )); then
-	[[ -x /usr/bin/mawk ]] && awk=mawk || awk=awk
+if ! [ $opt_duration -eq 0 ]; then
+	[ -x /usr/bin/mawk ] && awk=mawk || awk=awk
 else
 	# workarounds for mawk/gawk fflush behavior
-	if [[ -x /usr/bin/gawk ]]; then
+	if [ -x /usr/bin/gawk ]; then
 		awk=gawk
-	elif [[ -x /usr/bin/mawk ]]; then
+	elif [ -x /usr/bin/mawk ]; then
 		awk="mawk -W interactive"
 	else
 		awk=awk
@@ -158,27 +158,27 @@ cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
     debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### ftrace lock
-[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
+[ -e $flock ] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
 echo $$ > $flock || die "ERROR: unable to write $flock."
 wroteflock=1
 
 ### build probe
-if [[ -x /usr/bin/getconf ]]; then
+if [ -x /usr/bin/getconf ]; then
 	bits=$(getconf LONG_BIT)
 else
-	bits=64
-	[[ $(uname -m) == i* ]] && bits=32
+	mem_address=$(head -1 /proc/kallsyms | cut -f1 -d' ')
+	bits=$((  ${#mem_address} * 4 ))
 fi
-(( offset = bits / 8 ))
-function makeprobe {
+offset=$(( bits / 8 ))
+makeprobe() {
 	func=$1
 	kname=execsnoop_$func
 	kprobe="p:$kname $func"
 	i=0
-	while (( i < argc + 1 )); do
+	while [ $i -lt $(( argc + 1 )) ]; do
 		# p:kname do_execve +0(+0(%si)):string +0(+8(%si)):string ...
 		kprobe="$kprobe +0(+$(( i * offset ))(%si)):string"
-		(( i++ ))
+		i=$(( i + 1 ))
 	done
 }
 # try in this order: sys_execve, stub_execve, do_execve
@@ -186,23 +186,23 @@ makeprobe sys_execve
 
 ### setup and begin tracing
 echo nop > current_tracer
-if ! echo $kprobe >> kprobe_events 2>/dev/null; then
+if ! echo "$kprobe" >> kprobe_events 2>/dev/null; then
 	makeprobe stub_execve
-	if ! echo $kprobe >> kprobe_events 2>/dev/null; then
+	if ! echo "$kprobe" >> kprobe_events 2>/dev/null; then
 	    makeprobe do_execve
-	    if ! echo $kprobe >> kprobe_events 2>/dev/null; then
+	    if ! echo "$kprobe" >> kprobe_events 2>/dev/null; then
 		    edie "ERROR: adding a kprobe for execve. Exiting."
         fi
 	fi
 fi
-if ! echo 1 > events/kprobes/$kname/enable; then
+if ! echo 1 > "events/kprobes/$kname/enable"; then
 	edie "ERROR: enabling kprobe for execve. Exiting."
 fi
 if ! echo 1 > events/sched/sched_process_fork/enable; then
 	edie "ERROR: enabling sched:sched_process_fork tracepoint. Exiting."
 fi
 echo "Instrumenting $func"
-(( opt_time )) && printf "%-16s " "TIMEs"
+! [ $opt_time -eq 0 ] && printf "%-16s " "TIMEs"
 printf "%6s %6s %s\n" "PID" "PPID" "ARGS"
 
 #
@@ -218,15 +218,15 @@ offset=$($awk 'BEGIN { o = 0; }
 
 ### print trace buffer
 warn "echo > trace"
-( if (( opt_duration )); then
+( if ! [ $opt_duration -eq 0 ]; then
 	# wait then dump buffer
-	sleep $duration
-	cat -v trace
+	sleep "$duration"
+	cat trace
 else
 	# print buffer live
-	cat -v trace_pipe
-fi ) | $awk -v o=$offset -v opt_name=$opt_name -v name=$name \
-    -v opt_duration=$opt_duration -v opt_time=$opt_time -v kname=$kname \
+	cat trace_pipe
+fi ) | $awk -v o="$offset" -v opt_name=$opt_name -v name="$name" \
+    -v opt_duration=$opt_duration -v opt_time=$opt_time -v kname="$kname" \
     -v opt_reexec=$opt_reexec '
 	# common fields
 	$1 != "#" {
diff --git a/fs/cachestat b/fs/cachestat
--- a/fs/cachestat
+++ b/fs/cachestat
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # cachestat - show Linux page cache hit/miss statistics.
 #             Uses Linux ftrace.
@@ -58,7 +58,7 @@ tracing=/sys/kernel/debug/tracing
 interval=1; opt_timestamp=0; opt_debug=0
 trap 'quit=1' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: cachestat [-Dht] [interval]
 	                 -D              # print debug counters
@@ -74,13 +74,13 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
@@ -94,10 +94,10 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 ### option logic
-if (( $# )); then
+if ! [ $# -eq 0 ]; then
 	interval=$1
 fi
 echo "Counting cache functions... Output every $interval seconds."
@@ -107,7 +107,7 @@ cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
     debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### enable tracing
-sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
+echo 1 > /proc/sys/kernel/ftrace_enabled	# doesn't set exit status
 printf "mark_page_accessed\nmark_buffer_dirty\nadd_to_page_cache_lru\naccount_page_dirtied\n" > set_ftrace_filter || \
     die "ERROR: tracing these four kernel functions: mark_page_accessed,"\
     "mark_buffer_dirty, add_to_page_cache_lru and account_page_dirtied (unknown kernel version?). Exiting."
@@ -117,22 +117,22 @@ if ! echo 1 > function_profile_enabled; then
 	die "ERROR: enabling function profiling. Have CONFIG_FUNCTION_PROFILER? Exiting."
 fi
 
-(( opt_timestamp )) && printf "%-8s " TIME
+! [ $opt_timestamp -eq 0 ] && printf "%-8s " TIME
 printf "%8s %8s %8s %8s %12s %10s" HITS MISSES DIRTIES RATIO "BUFFERS_MB" "CACHE_MB"
-(( opt_debug )) && printf "  DEBUG"
+! [ $opt_debug -eq 0 ] && printf "  DEBUG"
 echo
 
 ### summarize
 quit=0
-while (( !quit )); do
+while [ $quit -eq 0 ]; do
 	echo 0 > function_profile_enabled
 	echo 1 > function_profile_enabled
-	sleep $interval
+	sleep "$interval"
 
-	(( opt_timestamp )) && printf "%(%H:%M:%S)T " -1
+	! [ $opt_timestamp -eq 0 ] && timestamp="$(date +%H:%M:%S) "
 
 	# cat both meminfo and trace stats, and let awk pick them apart
-	cat /proc/meminfo trace_stat/function* | awk -v debug=$opt_debug '
+	cat /proc/meminfo trace_stat/function* | awk -v debug=$opt_debug -v timestamp="$timestamp" '
 	# match meminfo stats:
 	$1 == "Buffers:" && $3 == "kB" { buffers_mb = $2 / 1024 }
 	$1 == "Cached:" && $3 == "kB" { cached_mb = $2 / 1024 }
@@ -151,7 +151,7 @@ while (( !quit )); do
 		hits = total - misses
 
 		ratio = 100 * hits / total
-		printf "%8d %8d %8d %7.1f%% %12.0f %10.0f", hits, misses, mbd,
+		printf "%s%8d %8d %8d %7.1f%% %12.0f %10.0f", timestamp, hits, misses, mbd,
 		    ratio, buffers_mb, cached_mb
 		if (debug)
 			printf "  (%d %d %d %d)", mpa, mbd, apcl, apd
diff --git a/kernel/funccount b/kernel/funccount
--- a/kernel/funccount
+++ b/kernel/funccount
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # funccount - count kernel function calls matching specified wildcards.
 #             Uses Linux ftrace.
@@ -45,7 +45,7 @@ opt_duration=0; duration=; opt_interval=0; interval=999999; opt_timestamp=0
 opt_tail=0; tcmd=cat; ttext=
 trap 'quit=1' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: funccount [-hT] [-i secs] [-d secs] [-t top] funcstring
 	                 -d seconds      # total duration of trace
@@ -65,13 +65,13 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
@@ -87,28 +87,28 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 ### option logic
-(( $# == 0 )) && usage
+[ $# -eq 0 ] && usage
 funcs="$1"
-if (( opt_tail )); then
+if ! [ $opt_tail -eq 0 ]; then
 	tcmd="tail -$tnum"
 	ttext=" Top $tnum only."
 fi
-if (( opt_duration )); then
+if ! [ $opt_duration -eq 0 ]; then
 	echo "Tracing \"$funcs\" for $duration seconds.$ttext.."
 else
 	echo "Tracing \"$funcs\".$ttext.. Ctrl-C to end."
 fi
-(( opt_duration && !opt_interval )) && interval=$duration
+! [ $opt_duration -eq 0 ] && [ $opt_interval -eq 0 ] && interval=$duration
 
 ### check permissions
 cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
     debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### enable tracing
-sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
+echo 1 > /proc/sys/kernel/ftrace_enabled	# doesn't set exit status
 echo "$funcs" > set_ftrace_filter || die "ERROR: enabling \"$funcs\". Exiting."
 warn "echo nop > current_tracer"
 if ! echo 1 > function_profile_enabled; then
@@ -119,14 +119,14 @@ fi
 
 ### summarize
 quit=0; secs=0
-while (( !quit && (!opt_duration || secs < duration) )); do
-	(( secs += interval ))
+while [ $quit -eq 0 ] && [ $opt_duration -eq 0 ] || [ $secs -lt "$duration" ]; do
+	secs=$(( secs + interval ))
 	echo 0 > function_profile_enabled
 	echo 1 > function_profile_enabled
-	sleep $interval
+	sleep "$interval"
 
 	echo
-	(( opt_timestamp )) && date
+	! [ $opt_timestamp -eq 0 ] && date
 	printf "%-30s %8s\n" "FUNC" "COUNT"
 
 	cat trace_stat/function* | awk '
diff --git a/kernel/funcgraph b/kernel/funcgraph
--- a/kernel/funcgraph
+++ b/kernel/funcgraph
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # funcgraph - trace kernel function graph, showing child function calls.
 #             Uses Linux ftrace.
@@ -73,7 +73,7 @@ opt_headers=0; opt_proc=0; opt_time=0; opt_tail=0; opt_nodur=0; opt_cpu=0
 opt_max=0; max=0
 trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: funcgraph [-aCDhHPtT] [-m maxdepth] [-p PID] [-L TID] [-d secs] funcstring
 	                 -a              # all info (same as -HPt)
@@ -100,39 +100,39 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function end {
+end() {
 	# disable tracing
 	echo 2>/dev/null
 	echo "Ending tracing..." 2>/dev/null
 	cd $tracing
 
-	(( opt_time )) && warn "echo nofuncgraph-abstime > trace_options"
-	(( opt_proc )) && warn "echo nofuncgraph-proc > trace_options"
-	(( opt_tail )) && warn "echo nofuncgraph-tail > trace_options"
-	(( opt_nodur )) && warn "echo funcgraph-duration > trace_options"
-	(( opt_cpu )) && warn "echo sleep-time > trace_options"
+	! [ $opt_time -eq 0 ] && warn "echo nofuncgraph-abstime > trace_options"
+	! [ $opt_proc -eq 0 ] && warn "echo nofuncgraph-proc > trace_options"
+	! [ $opt_tail -eq 0 ] && warn "echo nofuncgraph-tail > trace_options"
+	! [ $opt_nodur -eq 0 ] && warn "echo funcgraph-duration > trace_options"
+	! [ $opt_cpu -eq 0 ] && "echo sleep-time > trace_options"
 
 	warn "echo nop > current_tracer"
-	(( opt_pid || opt_tid )) && warn "echo > set_ftrace_pid"
-	(( opt_max )) && warn "echo 0 > max_graph_depth"
+	! [ $opt_pid -eq 0 ] || ! [ $opt_tid -eq 0 ] && warn "echo > set_ftrace_pid"
+	! [ $opt_max -eq 0 ] && warn "echo 0 > max_graph_depth"
 	warn "echo > set_graph_function"
 	warn "echo > trace"
 
-	(( wroteflock )) && warn "rm $flock"
+	! [ "$wroteflock" -eq 0 ] && warn "rm $flock"
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
 
-function edie {
+edie() {
 	# die with a quiet end()
 	echo >&2 "$@"
 	exec >/dev/null 2>&1
@@ -158,15 +158,15 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 ### option logic
-(( $# == 0 )) && usage
-(( opt_pid && opt_tid )) && edie "ERROR: You can use -p or -L but not both."
+[ $# -eq 0 ] && usage
+! [ $opt_pid -eq 0 ] && ! [ $opt_tid -eq 0 ] && edie "ERROR: You can use -p or -L but not both."
 funcs="$1"
-(( opt_pid )) && pidtext=" for PID $pid"
-(( opt_tid )) && pidtext=" for TID $tid"
-if (( opt_duration )); then
+! [ $opt_pid -eq 0 ] && pidtext=" for PID $pid"
+! [ $opt_tid -eq 0 ] && pidtext=" for TID $tid"
+if ! [ $opt_duration -eq 0 ]; then
 	echo "Tracing \"$funcs\"$pidtext for $duration seconds..."
 else
 	echo "Tracing \"$funcs\"$pidtext... Ctrl-C to end."
@@ -177,30 +177,32 @@ cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
     debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### ftrace lock
-[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
+[ -e $flock ] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
 echo $$ > $flock || die "ERROR: unable to write $flock."
 wroteflock=1
 
 ### setup and commence tracing
-sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
-read mode < current_tracer
-[[ "$mode" != "nop" ]] && edie "ERROR: ftrace active (current_tracer=$mode)"
-if (( opt_max )); then
-	if ! echo $max > max_graph_depth; then
+echo 1 > /proc/sys/kernel/ftrace_enabled
+read -r mode < current_tracer
+if [ "$mode" != "nop" ]; then
+	edie "ERROR: ftrace active (current_tracer=$mode)"
+fi
+if ! [ $opt_max -eq 0 ]; then
+	if ! echo "$max" > max_graph_depth; then
 		edie "ERROR: setting -m $max. Older kernel version? Exiting."
 	fi
 fi
-if (( opt_pid )); then
+if ! [ $opt_pid -eq 0 ]; then
     echo > set_ftrace_pid
     # ftrace expects kernel pids, which are thread ids
     for tid in /proc/$pid/task/*; do
-        if ! echo ${tid##*/} >> set_ftrace_pid; then
+        if ! echo "$tid" | cut -d/ -f3 >> set_ftrace_pid; then
             edie "ERROR: setting -p $pid (PID exist?). Exiting."
         fi
     done
 fi
-if (( opt_tid )); then
-    if ! echo $tid > set_ftrace_pid; then
+if ! [ $opt_tid -eq 0 ]; then
+    if ! echo "$tid" > set_ftrace_pid; then
         edie "ERROR: setting -L $tid (TID exist?). Exiting."
     fi
 fi
@@ -213,28 +215,28 @@ fi
 if ! echo function_graph > current_tracer; then
 	edie "ERROR: setting current_tracer to \"function\". Exiting."
 fi
-if (( opt_cpu )); then
+if ! [ $opt_cpu -eq 0 ]; then
 	if ! echo nosleep-time > trace_options; then
 		edie "ERROR: setting -C (nosleep-time). Exiting."
 	fi
 fi
 # the following must be done after setting current_tracer
-if (( opt_time )); then
+if ! [ $opt_time -eq 0 ]; then
 	if ! echo funcgraph-abstime > trace_options; then
 		edie "ERROR: setting -t (funcgraph-abstime). Exiting."
 	fi
 fi
-if (( opt_proc )); then
+if ! [ $opt_proc -eq 0 ]; then
 	if ! echo funcgraph-proc > trace_options; then
 		edie "ERROR: setting -P (funcgraph-proc). Exiting."
 	fi
 fi
-if (( opt_tail )); then
+if ! [ $opt_tail -eq 0 ]; then
 	if ! echo funcgraph-tail > trace_options; then
 		edie "ERROR: setting -T (funcgraph-tail). Old kernel? Exiting."
 	fi
 fi
-if (( opt_nodur )); then
+if ! [ $opt_nodur -eq 0 ]; then
 	if ! echo nofuncgraph-duration > trace_options; then
 		edie "ERROR: setting -D (nofuncgraph-duration). Exiting."
 	fi
@@ -242,16 +244,16 @@ fi
 
 ### print trace buffer
 warn "echo > trace"
-if (( opt_duration )); then
-	sleep $duration
-	if (( opt_headers )); then
+if ! [ $opt_duration -eq 0 ]; then
+	sleep "$duration"
+	if ! [ $opt_headers -eq 0 ]; then
 		cat trace
 	else
 		grep -v '^#' trace
 	fi
 else
 	# trace_pipe lack headers, so fetch them from trace
-	(( opt_headers )) && cat trace
+	! [ $opt_headers -eq 0 ] && cat trace
 	cat trace_pipe
 fi
 
diff --git a/kernel/functrace b/kernel/functrace
--- a/kernel/functrace
+++ b/kernel/functrace
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # functrace - trace kernel function calls matching specified wildcards.
 #             Uses Linux ftrace.
@@ -63,7 +63,7 @@ opt_duration=0; duration=; opt_pid=0; pid=; opt_tid=0; tid=; pidtext=
 opt_headers=0
 trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: functrace [-hH] [-p PID] [-L TID] [-d secs] funcstring
 	                 -d seconds      # trace duration, and use buffers
@@ -83,30 +83,30 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function end {
+end() {
 	# disable tracing
 	echo 2>/dev/null
 	echo "Ending tracing..." 2>/dev/null
 	cd $tracing
 	warn "echo nop > current_tracer"
-	(( opt_pid || opt_tid )) && warn "echo > set_ftrace_pid"
+	! [ $opt_pid -eq 0 ] || ! [ $opt_tid -eq 0 ] && warn "echo > set_ftrace_pid"
 	warn "echo > set_ftrace_filter"
 	warn "echo > trace"
-	(( wroteflock )) && warn "rm $flock"
+	! [ "$wroteflock" -eq 0 ] && warn "rm $flock"
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
 
-function edie {
+edie() {
 	# die with a quiet end()
 	echo >&2 "$@"
 	exec >/dev/null 2>&1
@@ -125,15 +125,15 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 ### option logic
-(( $# == 0 )) && usage
-(( opt_pid && opt_tid )) && edie "ERROR: You can use -p or -L but not both."
+[ $# -eq 0 ] && usage
+! [ $opt_pid -eq 0 ] && ! [ $opt_tid -eq 0 ] && edie "ERROR: You can use -p or -L but not both."
 funcs="$1"
-(( opt_pid )) && pidtext=" for PID $pid"
-(( opt_tid )) && pidtext=" for TID $pid"
-if (( opt_duration )); then
+! [ $opt_pid -eq 0 ] && pidtext=" for PID $pid"
+! [ $opt_tid -eq 0 ] && pidtext=" for TID $pid"
+if ! [ $opt_duration -eq 0 ]; then
 	echo "Tracing \"$funcs\"$pidtext for $duration seconds..."
 else
 	echo "Tracing \"$funcs\"$pidtext... Ctrl-C to end."
@@ -144,25 +144,25 @@ cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
     debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### ftrace lock
-[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
+[ -e $flock ] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
 echo $$ > $flock || die "ERROR: unable to write $flock."
 wroteflock=1
 
 ### setup and commence tracing
-sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
-read mode < current_tracer
-[[ "$mode" != "nop" ]] && edie "ERROR: ftrace active (current_tracer=$mode)"
-if (( opt_pid )); then
+echo 1 > /proc/sys/kernel/ftrace_enabled      # doesn't set exit status
+read -r mode < current_tracer
+[ "$mode" != "nop" ] && edie "ERROR: ftrace active (current_tracer=$mode)"
+if ! [ $opt_pid -eq 0 ]; then
     echo > set_ftrace_pid
     # ftrace expects kernel pids, which are thread ids
     for tid in /proc/$pid/task/*; do
-        if ! echo ${tid##*/} >> set_ftrace_pid; then
+        if ! echo "$tid" | cut -d/ -f3 >> set_ftrace_pid; then
             edie "ERROR: setting -p $pid (PID exist?). Exiting."
         fi
     done
 fi
-if (( opt_tid )); then
-    if ! echo $tid > set_ftrace_pid; then
+if ! [ $opt_tid -eq 0 ]; then
+    if ! echo "$tid" > set_ftrace_pid; then
         edie "ERROR: setting -L $tid (TID exist?). Exiting."
     fi
 fi
@@ -175,16 +175,16 @@ fi
 
 ### print trace buffer
 warn "echo > trace"
-if (( opt_duration )); then
-	sleep $duration
-	if (( opt_headers )); then
+if ! [ $opt_duration -eq 0 ]; then
+	sleep "$duration"
+	if ! [ $opt_headers -eq 0 ]; then
 		cat trace
 	else
 		grep -v '^#' trace
 	fi
 else
 	# trace_pipe lack headers, so fetch them from trace
-	(( opt_headers )) && cat trace
+	! [ $opt_headers -eq 0 ] && cat trace
 	cat trace_pipe
 fi
 
diff --git a/kernel/kprobe b/kernel/kprobe
--- a/kernel/kprobe
+++ b/kernel/kprobe
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # kprobe - trace a given kprobe definition. Kernel dynamic tracing.
 #          Written using Linux ftrace.
@@ -55,7 +55,7 @@ opt_filter=0; filter=; opt_view=0; opt_headers=0; opt_stack=0; dmesg=2
 debug=0; opt_force=0
 trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: kprobe [-FhHsv] [-d secs] [-p PID] [-L TID] kprobe_definition [filter]
 	                 -F              # force. trace despite warnings.
@@ -92,33 +92,32 @@ END
 	exit
 }
 
-function warn {
-	if ! eval "$@"; then
-		echo >&2 "WARNING: command failed \"$@\""
+warn() {
+	msg=shift
+	if ! eval "$msg"; then
+		echo >&2 "WARNING: command failed \"${msg}\""
 	fi
 }
 
-function end {
+end() {
 	# disable tracing
 	echo 2>/dev/null
 	echo "Ending tracing..." 2>/dev/null
-	cd $tracing
+	cd "$tracing"
 	warn "echo 0 > events/kprobes/$kname/enable"
-	if (( opt_filter )); then
-		warn "echo 0 > events/kprobes/$kname/filter"
-	fi
+	! [ $opt_filter -eq 0 ] && warn "echo 0 > events/kprobes/$kname/filter"
 	warn "echo -:$kname >> kprobe_events"
-	(( opt_stack )) && warn "echo 0 > options/stacktrace"
+	! [ $opt_stack -eq 0 ] && warn "echo 0 > options/stacktrace"
 	warn "echo > trace"
-	(( wroteflock )) && warn "rm $flock"
+	! [ $wroteflock -eq 0 ] && warn "rm $flock"
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
 
-function edie {
+edie() {
 	# die with a quiet end()
 	echo >&2 "$@"
 	exec >/dev/null 2>&1
@@ -140,36 +139,41 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
-(( $# )) || usage
+shift $(( OPTIND - 1 ))
+[ $# -eq 0 ] && usage
 kprobe=$1
 shift
-if (( $# )); then
+if [ $# -ne 0 ]; then
 	opt_filter=1
 	filter=$1
 fi
 
 ### option logic
-(( opt_pid + opt_filter + opt_tid > 1 )) && \
+[ $(( opt_pid + opt_filter + opt_tid )) -gt 1 ] && \
 	die "ERROR: use at most one of -p, -L, or filter."
-(( opt_duration && opt_view )) && die "ERROR: use either -d or -v."
-if (( opt_pid )); then
+[ $(( opt_duration + opt_view )) -gt 1 ] && die "ERROR: use either -d or -v."
+if ! [ $opt_pid -eq 0 ]; then
 	# convert to filter
 	opt_filter=1
 	# ftrace common_pid is thread id from user's perspective
 	for tid in /proc/$pid/task/*; do
-		filter="$filter || common_pid == ${tid##*/}"
+		filter="$filter || common_pid == $(echo "$tid" | cut -d/ -f3)"
 	done
-	filter=${filter:3}  # trim leading ' || ' (four characters)
+	filter=$(echo "$filter" | cut -b 4-)  # trim leading ' || ' (four characters)
 fi
-if (( opt_tid )); then
+if ! [ $opt_tid -eq 0 ]; then
 	opt_filter=1
 	filter="common_pid == $tid"
 fi
-if [[ "$kprobe" != p:* && "$kprobe" != r:* ]]; then
+case ${kprobe} in
+	p:*|r:*)
+		# This is okay, let it pass
+		;;
+	*)
 	echo >&2 "ERROR: invalid kprobe definition (should start with p: or r:)"
+	echo "kprobe: ${kprobe}"
 	usage
-fi
+esac
 #
 # parse the following:
 # r:do_sys_open
@@ -182,15 +186,17 @@ fi
 # r:my_sys_open do_sys_open rval=$retval %ax
 # ... and examples from USAGE message
 #
-krest=${kprobe#*:}
-kname=${krest%% *}
-set -- $krest
-if [[ $2 == "" || $2 == *[=%\$]* ]]; then
+krest=$(echo "${kprobe}" | cut -d':' -f2-)
+kname=$(echo "${krest}" | cut -d' ' -f1)
+set -- "$krest"
+case $2 in
+	""|*[=%\$]*)
 	# if probe name unspecified, default to function name
-	ktype=${kprobe%%:*}
+	ktype=$(echo "${kprobe}" | cut -b1)
 	kprobe="$ktype:$kname $krest"
-fi
-if (( debug )); then
+		;;
+esac
+if ! [ $debug -eq 0 ]; then
 	echo "kname: $kname, kprobe: $kprobe"
 fi
 
@@ -201,7 +207,7 @@ cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
 ## check function
 set -- $kprobe
 fname=$2
-if (( !opt_force )) && ! grep -w $fname available_filter_functions >/dev/null \
+if [ $opt_force -eq 0 ] && ! grep -w "$fname" available_filter_functions >/dev/null \
     2>&1
 then
 	echo >&2 "ERROR: func $fname not in $PWD/available_filter_functions."
@@ -210,8 +216,8 @@ then
 	exit 1
 fi
 
-if (( !opt_view )); then
-	if (( opt_duration )); then
+if [ $opt_view -eq 0 ]; then
+	if ! [ $opt_duration -eq 0 ]; then
 		echo "Tracing kprobe $kname for $duration seconds (buffered)..."
 	else
 		echo "Tracing kprobe $kname. Ctrl-C to end."
@@ -219,7 +225,7 @@ if (( !opt_view )); then
 fi
 
 ### ftrace lock
-[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
+[ -e $flock ] && die "ERROR: ftrace may be in use by PID $(cat "$flock") $flock"
 echo $$ > $flock || die "ERROR: unable to write $flock."
 wroteflock=1
 
@@ -227,42 +233,42 @@ wroteflock=1
 echo nop > current_tracer
 if ! echo "$kprobe" >> kprobe_events; then
 	echo >&2 "ERROR: adding kprobe \"$kprobe\"."
-	if (( dmesg )); then
+	if ! [ $dmesg -eq 0 ]; then
 		echo >&2 "Last $dmesg dmesg entries (might contain reason):"
 		dmesg | tail -$dmesg | sed 's/^/    /'
 	fi
 	edie "Exiting."
 fi
-if (( opt_view )); then
-	cat events/kprobes/$kname/format
+if ! [ $opt_view -eq 0 ]; then
+	cat "events/kprobes/$kname/format"
 	edie ""
 fi
-if (( opt_filter )); then
-	if ! echo "$filter" > events/kprobes/$kname/filter; then
+if ! [ $opt_filter -eq 0 ]; then
+	if ! echo "$filter" > "events/kprobes/$kname/filter"; then
 		edie "ERROR: setting filter or -p. Exiting."
 	fi
 fi
-if (( opt_stack )); then
+if ! [ $opt_stack -eq 0 ]; then
 	if ! echo 1 > options/stacktrace; then
 		edie "ERROR: enabling stack traces (-s). Exiting"
 	fi
 fi
-if ! echo 1 > events/kprobes/$kname/enable; then
+if ! echo 1 > "events/kprobes/$kname/enable"; then
 	edie "ERROR: enabling kprobe $kname. Exiting."
 fi
 
 ### print trace buffer
 warn "echo > trace"
-if (( opt_duration )); then
-	sleep $duration
-	if (( opt_headers )); then
+if ! [ $opt_duration -eq 0 ]; then
+	sleep "$duration"
+	if ! [ $opt_headers -eq 0 ]; then
 		cat trace
 	else
 		grep -v '^#' trace
 	fi
 else
 	# trace_pipe lack headers, so fetch them from trace
-	(( opt_headers )) && cat trace
+	! [ $opt_headers -eq 0 ] && cat trace
 	cat trace_pipe
 fi
 
diff --git a/opensnoop b/opensnoop
--- a/opensnoop
+++ b/opensnoop
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # opensnoop - trace open() syscalls with file details.
 #             Written using Linux ftrace.
@@ -52,7 +52,7 @@ opt_duration=0; duration=; opt_name=0; name=; opt_pid=0; pid=; opt_tid=0; tid=
 ftext=; opt_time=0; opt_fail=0; opt_file=0; file=
 trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: opensnoop [-htx] [-d secs] [-p PID] [-L TID] [-n name] [filename]
 	                 -d seconds      # trace duration, and use buffers
@@ -75,13 +75,13 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function end {
+end() {
 	# disable tracing
 	echo 2>/dev/null
 	echo "Ending tracing..." 2>/dev/null
@@ -89,22 +89,22 @@ function end {
 	warn "echo 0 > events/kprobes/getnameprobe/enable"
 	warn "echo 0 > events/syscalls/sys_exit_open/enable"
 	warn "echo 0 > events/syscalls/sys_exit_openat/enable"
-	if (( opt_pid || opt_tid )); then
+	if ! [ $opt_pid -eq 0 ] || ! [ $opt_tid -eq 0 ]; then
 		warn "echo 0 > events/kprobes/getnameprobe/filter"
 		warn "echo 0 > events/syscalls/sys_exit_open/filter"
 		warn "echo 0 > events/syscalls/sys_exit_openat/filter"
 	fi
 	warn "echo -:getnameprobe >> kprobe_events"
 	warn "echo > trace"
-	(( wroteflock )) && warn "rm $flock"
+	! [ $wroteflock -eq 0 ] && warn "rm $flock"
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
 
-function edie {
+edie() {
 	# die with a quiet end()
 	echo >&2 "$@"
 	exec >/dev/null 2>&1
@@ -125,67 +125,71 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
-if (( $# )); then
+
+shift $(( OPTIND - 1 ))
+if ! [ $# -eq 0 ]; then
 	opt_file=1
 	file=$1
 	shift
 fi
-(( $# )) && usage
+! [ $# -eq 0 ] && usage
 
 ### option logic
-(( opt_pid + opt_name + opt_tid > 1 )) && \
+[ $(( opt_pid + opt_name + opt_tid )) -gt 1 ] && \
 	die "ERROR: use at most one of -p, -n, -L."
-(( opt_pid )) && ftext=" issued by PID $pid"
-(( opt_tid )) && ftext=" issued by TID $tid"
-(( opt_name )) && ftext=" issued by process name \"$name\""
-(( opt_file )) && ftext="$ftext for filenames containing \"$file\""
-if (( opt_duration )); then
+! [ $opt_pid -eq 0 ] && ftext=" issued by PID $pid"
+! [ $opt_tid -eq 0 ] && ftext=" issued by TID $tid"
+! [ $opt_name -eq 0 ] && ftext=" issued by process name \"$name\""
+! [ $opt_file -eq 0 ] && ftext="$ftext for filenames containing \"$file\""
+if ! [ $opt_duration -eq 0 ]; then
 	echo "Tracing open()s$ftext for $duration seconds (buffered)..."
 else
 	echo "Tracing open()s$ftext. Ctrl-C to end."
 fi
 
 ### select awk
-(( opt_duration )) && use=mawk || use=gawk	# workaround for mawk fflush()
-[[ -x /usr/bin/$use ]] && awk=$use || awk=awk
+! [ $opt_duration -eq 0 ] && use=mawk || use=gawk	# workaround for mawk fflush()
+[ -x /usr/bin/$use ] && awk=$use || awk=awk
 
 ### check permissions
 cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
     debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### ftrace lock
-[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
+[ -e $flock ] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
 echo $$ > $flock || die "ERROR: unable to write $flock."
 wroteflock=1
 
 ### setup and begin tracing
 echo nop > current_tracer
 ver=$(uname -r)
-if [[ "$ver" == 2.* || "$ver" == 3.[1-6].* ]]; then
-	# rval is char *
-	kprobe='r:getnameprobe getname +0($retval):string'
-else
-	# rval is struct filename *
-	kprobe='r:getnameprobe getname +0(+0($retval)):string'
-fi
-if ! echo $kprobe >> kprobe_events; then
+case ${ver} in
+	2.*|3.*)
+		# rval is char *
+		kprobe='r:getnameprobe getname +0($retval):string'
+		;;
+	*)
+		# rval is struct filename *
+		kprobe='r:getnameprobe getname +0(+0($retval)):string'
+		;;
+esac
+if ! echo "$kprobe" >> kprobe_events; then
 	edie "ERROR: adding a kprobe for getname(). Exiting."
 fi
-if (( opt_pid )); then
+if ! [ $opt_pid -eq 0 ]; then
 	filter=
 	for tid in /proc/$pid/task/*; do
-		filter="$filter || common_pid == ${tid##*/}"
+		filter="$filter || common_pid == $(echo "$tid" | cut -d/ -f3)"
 	done
-	filter=${filter:3}  # trim leading ' || ' (four characters)
-	if ! echo $filter > events/kprobes/getnameprobe/filter || \
+	filter=$(echo "$filter" | cut -b 4-)  # trim leading ' || ' (four characters)
+	if ! echo "$filter" > events/kprobes/getnameprobe/filter || \
 	    ! echo $filter > events/syscalls/sys_exit_open/filter || \
 	    ! echo $filter > events/syscalls/sys_exit_openat/filter
 	then
 	    edie "ERROR: setting -p $pid. Exiting."
 	fi
 fi
-if (( opt_tid )); then
+if ! [ $opt_tid -eq 0 ]; then
 	if ! echo "common_pid == $tid" > events/kprobes/getnameprobe/filter || \
 	    ! echo "common_pid == $tid" > events/syscalls/sys_exit_open/filter || \
 	    ! echo "common_pid == $tid" > events/syscalls/sys_exit_openat/filter
@@ -202,7 +206,7 @@ fi
 if ! echo 1 > events/syscalls/sys_exit_openat/enable; then
 	edie "ERROR: enabling openat() exit tracepoint. Exiting."
 fi
-(( opt_time )) && printf "%-16s " "TIMEs"
+! [ $opt_time -eq 0 ] && printf "%-16s " "TIMEs"
 printf "%-16.16s %-6s %4s %s\n" "COMM" "PID" "FD" "FILE"
 
 #
@@ -218,9 +222,9 @@ offset=$($awk 'BEGIN { o = 0; }
 
 ### print trace buffer
 warn "echo > trace"
-( if (( opt_duration )); then
+( if ! [ $opt_duration -eq 0 ]; then
 	# wait then dump buffer
-	sleep $duration
+	sleep "$duration"
 	cat trace
 else
 	# print buffer live
diff --git a/tools/reset-ftrace b/tools/reset-ftrace
--- a/tools/reset-ftrace
+++ b/tools/reset-ftrace
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # reset-ftrace - reset state of ftrace, disabling all tracing.
 #                Written for Linux ftrace.
@@ -40,7 +40,7 @@ tracing=/sys/kernel/debug/tracing
 flock=/var/tmp/.ftrace-lock
 opt_force=0; opt_quiet=0
 
-function usage {
+usage() {
 	cat <<-END >&2
 	USAGE: reset-ftrace [-fhq]
 	                 -f              # force: delete ftrace lock file
@@ -52,35 +52,35 @@ END
 	exit
 }
 
-function warn {
+warn() {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
 }
 
-function die {
+die() {
 	echo >&2 "$@"
 	exit 1
 }
 
-function vecho {
-	(( opt_quiet )) && return
+vecho() {
+	! [ $opt_quiet -eq 0 ] && return
 	echo "$@"
 }
 
 # write to file
-function writefile {
+writefile() {
 	file=$1
 	string=$2	# optional
-	if [[ ! -w $file ]]; then
+	if ! [ -w "$file" ]; then
 		echo >&2 "WARNING: file $file not writable/exists. Skipping."
 		return
 	fi
 	vecho "$file, before:"
-	(( ! opt_quiet )) && cat -n $file
+	[ $opt_quiet -eq 0 ] && awk <"$file" '{ print "    " NR "\t" $0; }'
 	warn "echo $string > $file"
 	vecho "$file, after:"
-	(( ! opt_quiet )) && cat -n $file
+	[ $opt_quiet -eq 0 ] && awk <"$file" '{ print "    " NR "\t" $0; }'
 	vecho
 }
 
@@ -93,15 +93,16 @@ do
 	h|?)	usage ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 ### ftrace lock
-if [[ -e $flock ]]; then
-	if (( opt_force )); then
+if [ -e $flock ]; then
+	if [ $opt_force -eq 0 ]; then
 		warn rm $flock
 	else
-		echo -e >&2 "ERROR: ftrace lock ($flock) exists. It shows" \
-		    "ftrace may be in use by PID $(cat $flock).\nDouble check" \
+		echo >&2 "ERROR: ftrace lock ($flock) exists. It shows" \
+		    "ftrace may be in use by PID $(cat $flock).
+		    Double check" \
 		    "to see if that PID is still active. If not, consider" \
 		    "using -f to force a reset. Exiting."
 		exit 1
